spring:
  application:
    name: loan-management
  datasource:
    url: jdbc:h2:mem:loandb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

# CBS Integration Configuration
cbs:
  kyc:
    url: https://kycapitest.credable.io/service/customerWsdl.wsdl
    username: admin
    password: pwd123
  transaction:
    url: https://trxapitest.credable.io/service/transactionWsdl.wsdl
    username: admin
    password: pwd123

# Scoring Engine Configuration
scoring:
  base-url: https://scoringtest.credable.io/api/v1
  max-retries: 3
  retry-delay: 1000 # in milliseconds 